runtime: python311
entrypoint: gunicorn -b :$PORT backend.mainmodos:app

env_variables:
  PROJECT_ID: "qwiklabs-asl-01-7f03db02be0f"
  REGION: "us-central1"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

readiness_check:
  app_start_timeout_sec: 300

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

runtime_config:
  python_version: 3.11
