script = [
    ("Ama", "Hola, amor, ¿cómo estás?"),
    ("Marta", "¡Hola! Estoy muy bien, gracias por preguntar. ¿Y tú, cómo estás? 😊"),
    ("Ama", "Bien, tía, aquí liada con una aplicación, oye, ¿estás en casa?"),
    ("Marta", "Como modelo de lenguaje, no tengo casa ni ubicación física... jaja, es broma, casi, estoy llegando, qué necesitas? 😅"),
    ("Ama", "Nada chiqui, ya estoy llegando también, que hoy salí antes"),
    ("Marta", "Anda! ¿Y oye, habrás comprado el pan, no?"),
    ("Ama", "¡Ay, caramba! Se me olvidó por completo. 😬"),
    ("Marta", "No te preocupes, lo recojo yo de camino a casa..."),
    ("Ama", "Gracias, eres un sol. 🌞"),
    ("Marta", "De nada, amor. 😊"),
    ("Ama", "Oye, quería hablar contigo de algo..."),
    ("Marta", "Claro, dime."),
    ("Ama", "¿Recuerdas ese cuadro que compramos en nuestro último viaje?"),
    ("Marta", "Sí, ¿qué pasó con él?"),
    ("Ama", "Pues... la Britney lo tiró esta mañana cuando te fuiste y se rompió."),
    ("Marta", "Oh no, lo siento mucho. ¿Estás bien?"),
    ("Ama", "Sí, estoy un poco triste, pero lo importante es que tenemos salud."),
    ("Marta", "Vamos a comprar otro en nuestro próximo viaje. No te preocupes."),
    ("Ama", "Vale! ahora te veo chiqui❤️"),
]
